packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'

autoInstallPeers: false
strictPeerDependencies: true
engineStrict: true
nodeVersion: 24.18.0
pmOnFail: error
savePrefix: ''
verifyStoreIntegrity: true
updateNotifier: false
minimumReleaseAgeStrict: true

allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.7'
  - '@turbo/darwin-arm64@2.10.7'
  - '@turbo/linux-64@2.10.7'
  - '@turbo/linux-arm64@2.10.7'
  - '@turbo/windows-64@2.10.7'
  - '@turbo/windows-arm64@2.10.7'
  - turbo@2.10.7
